Repository yiisoft/form, pull requests merged in 2022-02, with the labels that each got.

#174 Add `replaceIndividualToken()` method.
  src/Widget/Attribute/FieldAttributes.php
  tests/Widget/Field/FieldTest.php
Labels: status:code review

#173 Update docs, fix phpdocs.
  docs/checkbox.md
  docs/checkboxlist.md
  docs/creating-forms.md
  docs/date.md
  docs/datetime.md
  docs/datetimelocal.md
  docs/email.md
  docs/error-summary.md
  docs/error.md
  docs/file.md
  docs/hint.md
  docs/label.md
  docs/number.md
  docs/password.md
  docs/radio.md
  docs/radiolist.md
  docs/range.md
  docs/resetbutton.md
  docs/select.md
  docs/submitbutton.md
  docs/telephone.md
  docs/text.md
  docs/url.md
  src/Widget/Attribute/GlobalAttributes.php
  src/Widget/Attribute/InputAttributes.php
  tests/Widget/FieldsetTest.php
Labels: status:code review

#178 Adapt after removing result set in validator
  src/FormModel.php
  tests/TestSupport/Form/PersonalForm.php
  tests/TestSupport/Validator/ValidatorMock.php
  tests/Widget/ErrorSummaryTest.php
Labels: type:bug

#180 Additions after changes in validator (PR #168)
  src/FormErrors.php
  src/FormErrorsInterface.php
  src/FormModel.php
Labels: type:task

#176 Update last changes `yiisoft\validator`.
  composer.json
  src/FormModel.php
  tests/FormModelTest.php
  tests/Helper/HtmlFormErrorsTest.php
  tests/TestSupport/Form/EachForm.php
  tests/TestSupport/Form/FormWithNestedAttribute.php
  tests/Validator/EachValidatorTest.php
Labels: status:code review

#175 Remove cast before validation.
  src/FormModel.php
  src/FormModelInterface.php
  tests/FormModelTest.php
Labels: status:code review

#182 Implement `setFormErrors()` method.
  psalm.xml
  src/FormModel.php
  src/FormModelInterface.php
  tests/FormModelTest.php
  tests/TestSupport/CustomFormErrors.php
Labels: status:code review

#181 Allow null, numeric or string `hidden::class` widget.
  src/Widget/Hidden.php
  tests/Widget/Field/FieldHiddenTest.php
  tests/Widget/HiddenTest.php
Labels: status:code review
