Repository yiisoft/form, pull requests merged in 2022-03, with the labels that each got.

#185 Fix Psalm - FormModelInterface::hasAttribute()
  src/FormModelInterface.php
Labels: type:bug

#184 Allow symbols in input name
  src/Helper/HtmlForm.php
  tests/Helper/HtmlFormTest.php
  tests/TestSupport/Form/DynamicFieldsForm.php
Labels: status:code review

#183 Sync validator changes
  .github/workflows/build.yml
  .github/workflows/static.yml
  composer.json
  docs/error-summary.md
  docs/error.md
  src/FormModel.php
  src/Widget/Validator/FieldValidator.php
  tests/TestSupport/Form/AttributesValidatorForm.php
  tests/TestSupport/Form/EachForm.php
  tests/TestSupport/Form/FormWithNestedAttribute.php
  tests/TestSupport/Form/LoginForm.php
  tests/TestSupport/Form/LoginValidatorForm.php
  tests/TestSupport/Form/PersonalForm.php
  tests/TestSupport/Form/ValidatorForm.php
  tests/Widget/EmailTest.php
  tests/Widget/Field/FieldEmailTest.php
  tests/Widget/Field/FieldPasswordTest.php
  tests/Widget/Field/FieldTelephoneTest.php
  tests/Widget/Field/FieldTextTest.php
  tests/Widget/Field/FieldUrlTest.php
  tests/Widget/PasswordTest.php
  tests/Widget/TelephoneTest.php
  tests/Widget/TextTest.php
  tests/Widget/UrlTest.php
Labels: type:task
